terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to open file 'experiments/neg/synthesis/fibo/program.txt'
